---
- hosts: k8smaster
  remote_user: vagrant
  become: true
  become_method: sudo
  vars:
      k8smaster_ipaddr: 192.168.56.151
  roles:
      - role: docker
      - role: k8s
      - role: k8smaster
