---
# Master Kubernetes

- name: Initialize master kubernete  
  command: kubeadm init --token {{ k8s_token  }} --api-advertise-addresses={{ k8smaster_ipaddr  }}
  register: init_log
  args: 
    creates: /etc/kubernetes/pki

- debug:
    var: init_log.stdout_lines

# Verify weave-kube exists
- name: Verify weave-kube
  command: bash -c "kubectl get pods --all-namespaces"
  ignore_errors: True
  register: verify_weave

# Install weave-net only once
- name: Applying weave-kube
  command: kubectl create -f https://git.io/weave-kube
  when: verify_weave.stdout.find('weave') == -1
